FROM python:3.13-slim
WORKDIR /app


COPY requirements.txt ./
RUN pip install --no-cache-dir -r requirements.txt

COPY src ./
COPY tests ./tests

COPY entrypoint.sh /entrypoint.sh
RUN chmod +x /entrypoint.sh

RUN useradd app
USER app

EXPOSE 8080

ENTRYPOINT ["/entrypoint.sh"]
CMD ["gunicorn","-b", "0.0.0.0:8080", "main:app"]